DIRECTION_LOOKUP_TABLE = {
    "zoom_in" : {"zoom" : "in",
                 "zoom_coef" : 5,
                 "trans":[0,0],
                 "trans_coef":[2,2],
                 "rotation":[0,0,0],
                 "rotation_coef":[1.5,1.5,1.5]},
    "zoom_out" : {"zoom": "out",
                  "zoom_coef": 5,
                 "trans":[0,0],
                 "trans_coef":[2,2],
                 "rotation":[0,0,0],
                 "rotation_coef":[1.5,1.5,1.5]},
    "translation_x": {"zoom": "None",
                  "zoom_coef": 5,
                 "trans":[1,0],
                 "trans_coef":[2,2],
                 "rotation":[0,0,0],
                 "rotation_coef":[1.5,1.5,1.5]},
    "translation_y": {"zoom": "None",
                  "zoom_coef": 5,
                 "trans":[0,1],
                 "trans_coef":[2,2],
                 "rotation":[0,0,0],
                 "rotation_coef":[1.5,1.5,1.5]},
    "rotation_x": {"zoom": "None",
                  "zoom_coef": 5,
                 "trans":[0,0],
                 "trans_coef":[2,2],
                 "rotation":[1,0,0],
                 "rotation_coef":[1.5,1.5,1.5]},
    "rotation_y": {"zoom": "None",
                  "zoom_coef": 5,
                 "trans":[0,0],
                 "trans_coef":[2,2],
                 "rotation":[0,1,0],
                 "rotation_coef":[1.5,1.5,1.5]},
    "rotation_z": {"zoom": "None",
                  "zoom_coef": 5,
                 "trans":[0,0],
                 "trans_coef":[2,2],
                 "rotation":[0,0,1],
                 "rotation_coef":[1.5,1.5,1.5]},
    "zoom_in_rotation_y": {"zoom": "in",
                  "zoom_coef": 5,
                 "trans":[0,0],
                 "trans_coef":[2,2],
                 "rotation":[0,1,0],
                 "rotation_coef":[1.5,1.5,1.5]},
                 }
